### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by tlhackque** [famzah/mod_fcgid#1]
https://bz.apache.org/bugzilla/show_bug.cgi?id=59656 references this work.

It also says:

> Here is the documentation for the new directive: http://www.famzah.net/temp/FcgidMaxProcessesUsedNoWait.docs.txt

That link has gone stale, and the documentation should be in this repo.

**Comment by famzah** [comment]
The documentation is in the README.md file of this repo.
